FROM alanfranz/fwd-centos-6:latest
MAINTAINER Andy Wick <andy.wick@teamaol.com>

RUN yum -y install wget centos-release-scl && wget -O /etc/yum.repos.d/ntop.repo http://packages.ntop.org/centos-stable/ntop.repo && yum clean all
RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
RUN yum -y install git curl pcre pcre-devel pkgconfig flex bison gcc gcc-c++ zlib-devel e2fsprogs-devel openssl-devel file-devel make gettext libuuid-devel perl-JSON bzip2-libs bzip2-devel perl-libwww-perl libpng-devel xz libffi-devel libselinux-python rpm-build readline-devel pfring devtoolset-3-toolchain

COPY .thirdparty/* release/thirdparty.sh release/versions.sh /tmp/
RUN sh -c /tmp/thirdparty.sh

ARG NAME
ENV NAME $NAME
COPY . /tmp/$NAME
RUN scl enable devtoolset-3 /tmp/$NAME/release/build.sh

ARG ITERATION
ARG VERSION
RUN fpm -s dir -t rpm -n $NAME -v $VERSION --iteration $ITERATION /data/$NAME

