FROM alanfranz/fwd-centos-7:latest
MAINTAINER Andy Wick <andy.wick@teamaol.com>

RUN yum clean all && yum -y install wget && wget -O /etc/yum.repos.d/ntop.repo http://packages.ntop.org/centos-stable/ntop.repo
RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN yum -y install git curl pcre pcre-devel pkgconfig flex bison gcc gcc-c++ zlib-devel e2fsprogs-devel openssl-devel file-devel make gettext libuuid-devel perl-JSON bzip2-libs bzip2-devel perl-libwww-perl libpng-devel xz libffi-devel libselinux-python rpm-build pfring readline-devel

COPY .thirdparty/* release/thirdparty.sh release/versions.sh /tmp/
RUN sh -c /tmp/thirdparty.sh

ARG NAME
ENV NAME $NAME
COPY . /tmp/$NAME
RUN sh -c /tmp/$NAME/release/build.sh

ARG ITERATION
ARG VERSION
RUN fpm -s dir -t rpm -n $NAME -v $VERSION --iteration $ITERATION /data/$NAME
