FROM ubuntu:xenial
MAINTAINER Andy Wick <andy.wick@teamaol.com>

#RUN apt-get update ; apt-get install -y wget curl lsb-release
#RUN wget -N http://apt-stable.ntop.org/14.04/all/apt-ntop-stable.deb ; dpkg --install apt-ntop-stable.deb
#RUN apt-get update; apt-get install -y pfring

ARG VERSION
ARG ITERATION
COPY builds/ubuntu-16/moloch_${VERSION}-${ITERATION}_amd64.deb /tmp
RUN dpkg -i /tmp/moloch_${VERSION}-${ITERATION}_amd64.deb

EXPOSE 8081
WORKDIR /data/moloch/wiseService
CMD ["/data/moloch/bin/node", "wiseService.js"]
