FROM ubuntu:16.04
MAINTAINER Andy Wick <andy.wick@teamaol.com>

ARG VERSION
ARG ITERATION
COPY builds/ubuntu-16/moloch_${VERSION}-${ITERATION}_amd64.deb /tmp
RUN dpkg -i /tmp/moloch_${VERSION}-${ITERATION}_amd64.deb

EXPOSE 8081
WORKDIR /data/moloch/wiseService
CMD ["/data/moloch/bin/node", "wiseService.js"]
