FROM alanfranz/fwd-ubuntu-xenial:latest
MAINTAINER Andy Wick <andy.wick@teamaol.com>

RUN apt-get update ; apt-get install -y git wget curl libpcre3-dev uuid-dev libmagic-dev pkg-config gcc g++ flex bison zlib1g-dev libffi-dev gettext make libjson-perl libbz2-dev libwww-perl libpng-dev xz-utils libffi-dev libssl-dev python-minimal lsb-release
RUN wget -N http://apt-stable.ntop.org/16.04/all/apt-ntop-stable.deb ; dpkg --install apt-ntop-stable.deb
RUN apt-get update; apt-get install -y pfring

COPY release/thirdparty.sh /tmp/
RUN sh -c /tmp/thirdparty.sh

COPY . /tmp/moloch
RUN sh -c /tmp/moloch/release/build.sh

ARG ITERATION
ARG VERSION
RUN fpm -s dir -t deb -n moloch -v $VERSION --iteration $ITERATION /data/moloch
